services:
  web:
    image: dimilan/checkinserver:AMD64
    networks:
      - cloudflare
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo:27017/clientDB
      - CLEANUP_KEY=your-very-long-secret-key-here
  mongo:
    image: mongo:latest
    networks:
      - cloudflare
    restart: always
networks:
    cloudflare:
      external: true
